"""Page selectors for web chats, carried over from Compact (read from the live sites). Override per site in
the node settings when a site changes its page."""

SITES = {'claude_web': {'new_url': 'https://claude.ai/new',
                'host': 'claude.ai',
                'chat_pattern': 'claude\\.ai/chat/[0-9a-f-]{8,}',
                'composer': '[data-testid="chat-input"], div.ProseMirror[contenteditable="true"]',
                'send_button': 'button[aria-label="Send message"]:not([disabled])',
                'stop_button': '[data-is-streaming="true"], button[aria-label="Stop response"]',
                'assistant_turn': '[data-is-streaming]',
                'user_turn': '[data-testid="user-message"]',
                'error_box': '[role="alert"]',
                'limit_patterns': ['this conversation is getting long',
                                   'conversation has reached its maximum length',
                                   'start a new chat'],
                'error_patterns': ['something went wrong', 'try again later'],
                'usage_patterns': ['message limit',
                                   'you are out of',
                                   'usage limit',
                                   'limit reached',
                                   "you've hit your",
                                   "you've reached your",
                                   'limit will reset',
                                   'limit resets',
                                   'out of free messages'],
                'mode_labels': {'chat': 'Claude', 'code': 'Code'},
                'attach_button': '[data-testid="chat-input-attach"]',
                'model_picker': '[data-testid="model-selector-dropdown"]',
                'approve_button_texts': ['Always allow', 'Allow always', 'Allow for this chat', 'Allow']},
 'gemini_web': {'new_url': 'https://gemini.google.com/app',
                'host': 'gemini.google.com',
                'own_window': True,
                'chat_pattern': 'gemini\\.google\\.com/app/[0-9a-z]{8,}',
                'composer': 'rich-textarea .ql-editor[contenteditable="true"]',
                'send_button': 'button[aria-label="Send message"]:not([disabled]):not([aria-disabled="true"])',
                'stop_button': 'button[aria-label^="Stop"], button.send-button.stop, mat-icon[fonticon="stop"]',
                'assistant_turn': 'message-content',
                'user_turn': 'user-query',
                'error_box': '[role="alert"], .error-message',
                'limit_patterns': ['this conversation is too long', 'start a new chat'],
                'error_patterns': ['something went wrong', 'try again later', "can't help with that right now"],
                'usage_patterns': ["you've reached your limit", 'reached your daily limit', 'limit resets']}}
