"""Generate docs/TOOLS.md from the live tool definitions (never out of date)."""
from __future__ import annotations

import inspect

from .plugins.common.batch import make_batch_spec
from .plugins.common.collab import build_collab_book
from .plugins.common.registrar import public_signature
from .plugins.pc.server import pc_specs


def _params(spec) -> str:
    out = []
    for name, p in public_signature(spec).parameters.items():
        out.append(name if p.default is inspect.Parameter.empty else f"{name}={p.default!r}")
    return ", ".join(out)


def all_sections() -> list[tuple[str, list]]:
    """(connector title, specs incl. its batch tool) exactly as the servers register them."""
    sections = []
    for kind, title, path in (("master", "EmaraAI Master", "/master"), ("agent", "EmaraAI Agent", "/agent")):
        specs = list(build_collab_book(session_kind=kind).specs)
        specs.append(make_batch_spec("hub_batch", title, specs))
        sections.append((f"{title}  ({path}/mcp)", specs))
    for group, label in (("core", "PC"), ("browser", "browser"), ("desktop", "desktop")):
        sections.append((f"EmaraAI Agent: {label} tools  (/agent/mcp)", pc_specs(group)))
    return sections


def render_tools_doc() -> str:
    lines = ["# EmaraAI Hub — tool catalog", "", "Generated by `python -m emaraai_hub tools-doc`. Do not edit by hand.", "",
             "Legend: 🔒 read-only · 📦 the connector's batch tool (several calls in one request). "
             "Every result is `{ok, result, next?, notices?}` or `{ok:false, error:{code, message, fix}}`.", ""]
    for title, specs in all_sections():
        lines += [f"## {title}", "", f"{len(specs)} tools.", "", "| Tool | Params | Purpose | Bridge call |", "|---|---|---|---|"]
        for s in specs:
            flags = (" 🔒" if s.readonly else "") + (" 📦" if s.is_batch else "")
            lines.append(f"| `{s.name}`{flags} | `{_params(s)}` | {s.summary} | {s.maps_to or '-'} |")
        lines.append("")
    return "\n".join(lines) + "\n"
