"""Write docs/TOOLS.md: the tools and actions a chat sees, taken from the real servers.

    .venv\\Scripts\\python.exe scripts\\compact_doc.py
"""
import asyncio
import json
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from emaraai_hub.infra.config import Settings  # noqa: E402
from emaraai_hub.infra.db import Database  # noqa: E402
from emaraai_hub.plugins.compact.surface import BATCH, TITLES  # noqa: E402
from emaraai_hub.plugins.agent.server import build_agent_server  # noqa: E402
from emaraai_hub.plugins.master.server import build_master_server  # noqa: E402
from emaraai_hub.runtime.hub import Hub  # noqa: E402


async def render(hub) -> str:
    out = ["# EmaraAI Hub 3.0 - the tools a chat sees", "",
           "Generated by `scripts/compact_doc.py` from the real servers. Every tool takes `action`; `action=\"help\", topic=\"<action>\"` "
           "returns one action's full parameters.",
           "`?` marks an optional parameter. `session_id` is accepted by every action and left out below.", ""]
    for plugin in ("master", "agent"):
        srv = {"master": build_master_server, "agent": build_agent_server}[plugin](hub)
        tools = await srv.list_tools()
        size = len(json.dumps([{"name": t.name, "description": t.description, "inputSchema": t.input_schema} for t in tools], separators=(",", ":")))
        out += [f"## {TITLES[plugin]}  (/{plugin}/mcp) - {len(tools)} tools, {size / 1000:.1f} KB", ""]
        for t in tools:
            lines = (t.description or "").split("\n")
            out += [f"### `{t.name}`", "", lines[0], ""]
            if t.name == BATCH:
                out += ["Several steps in one call, across any of the tools above: `steps=[{tool, action, ...parameters}]`. "
                        "`$N.field` reuses a value from step N. This is the preferred way to call.", ""]
                continue
            out += ["| Action | Parameters | Inner tool |", "|---|---|---|"]
            for action, (inner, _renames) in srv.table[t.name].items():
                sheet = srv._sheet(t.name, action)
                params = sheet[sheet.index("(") + 1:sheet.rindex(")")] if "(" in sheet else ""
                out.append(f"| `{action}` | `{params or '-'}` | {inner} |")
            out.append("")
    return "\n".join(out)


def main() -> None:
    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        s = Settings()
        s.base_dir, s.data_dir, s.logging.dir, s.logging.console = str(ROOT), tmp + "/data", tmp + "/logs", False
        s.config_file = tmp + "/config/hub.yaml"
        s.pc.warm_shells, s.pc.fast_shell = 0, False
        hub = Hub(s, db=Database(":memory:"))
        text = asyncio.run(render(hub))
    (ROOT / "docs" / "TOOLS.md").write_text(text, encoding="utf-8", newline="\n")
    print(text[:1500])


if __name__ == "__main__":
    main()
